### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by ai** [browserslist/browserslist-ga#10]
@dmfrancisco We need to update `randomatic`

**Comment by dmfrancisco** [comment]
@ai I noticed that too, thanks for opening the issue 👍 This is a dependency of Jest, which we use for testing. I've tried to update Jest to the latest version but they are still using an older version of this dependency.

**Comment by ai** [comment]
@dmfrancisco the issue is still in repo. You can hide the warning if it is not affecting real users.

**Comment by dmfrancisco** [comment]
@ai As far as I know users that are not contributors to the repository won't see the warning. But I agree with you and I'll take a look again at this soon 👍
