### ISSUE TITLE
Can't this lead to the reduction of your audience if stats were not optimal to start from?

### ISSUE THREAD

**Issue by everdimension** [browserslist/browserslist-ga#11]
Imagine this situation. The website did not take care of transpiling for the correct audience in the first place, and therefore it only sees users with the latest browsers in its analytics, because everyone else simply can't use it.

Based on the collected analytics data, `> 0.5% in my stats` would only make the matters worse, wouldn't it?

**Comment by dmfrancisco** [comment]
Sure, the goal is to optimize for your audience, so you need to know it well first. If you don't know your audience (you don't have enough data), there's no point in trying to optimize yet.

**Comment by dmfrancisco** [comment]
Do you think we should make this clearer in the readme? If so, could you send a PR with the change?
