### ISSUE TITLE
Packages need updating in general

### ISSUE THREAD

**Issue by ssong** [browserslist/browserslist-ga#27]
The prior fix upgraded only up to v38, the issue is patched in 39.1.0.

**Comment by ssong** [comment]
There are 141 high and 1 critical vulns in the current package list.

**Comment by dmfrancisco** [comment]
Can you explain what you mean by prior fix? Could you send a PR with your changes?

**Comment by ssong** [comment]
So this was the PR that got merged and was meant to have fixed it.


https://github.com/browserslist/browserslist-ga/pull/21

When I upgraded the packages today that I noticed that the audit warning was still there and it seems that it was upgraded to the wrong version? 

Tried to find out if there had been changes to the advisory or if I mistakenly thought that v38 was the patched version but I’m a tad bit baffled. 

But either way, willing to pick this one up if no one else has picked it up yet.
