### ISSUE TITLE
Browserslist org

### ISSUE THREAD

**Issue by ai** [browserslist/browserslist-ga#3]
I moved Browserslist and Browserslist Example to [Browserslist org](https://github.com/browserslist).

Let’s move `browserslist-ga` too :).

**Comment by dmfrancisco** [comment]
Thanks for coordinating this migration @ai 🙌I just sent you an email with some final details.

**Comment by ai** [comment]
Done. Now you are admin in this project.

сб, 24 мар. 2018 г., 9:03 David Francisco <notifications@github.com>:
