### ISSUE TITLE
empty ios_saf counts

### ISSUE THREAD

**Issue by randypuro** [browserslist/browserslist-ga#37]
`ios_saf` is current showing 0's for all versions.
A quick glance looks like `caniuse_parser.js` is keying on 'iOS Safari' whereas `const { agents } = require("caniuse-lite/dist/unpacker/agents"); agents.ios_saf.browser;` is 'Safari on iOS'

**Comment by MechanicalHuman** [comment]
@randypuro I can confirm that if `caniuse_parser.js` resolves the browser to `Safari on iOS` instead of `iOS Safari` the output has `ios_saf` count data

**Comment by elstgav** [comment]
I’ve opened a PR to fix this: #38
