### ISSUE TITLE
Publish 0.0.13?

### ISSUE THREAD

**Issue by michaeljaltamirano** [browserslist/browserslist-ga#39]
Hi,

I'm currently playing around with [browserslist-ga-export](https://github.com/browserslist/browserslist-ga-export) which relies on `browserslist-ga` under the hood. Because the [iOS Safari Usage](https://github.com/browserslist/browserslist-ga/pull/38) fix was merged in but not released as a new patch version, usage of `browserslist-ga-export` is not correctly parsing iOS Safari. 

Can we release a new patch version of `browserslist-ga`? I've modified the content in `node_modules` to match that PR as a temporary workaround but I'm also writing up steps to reproduce the work for generating the data and this is currently a blocker. Thanks!

**Comment by dmfrancisco** [comment]
Hey @michaeljaltamirano, should be there now. Sorry for the wait.

Just an FYI, you can also install the package directly from GitHub when you need updates that have not yet been published in the NPM registry.
