### ISSUE TITLE
Do not require Google login

### ISSUE THREAD

**Issue by galvarez421** [browserslist/browserslist-ga#6]
Supposing that a user does not want to log in to a Google account to take advantage of this tool, is there a possibility that this tool could allow the user to specify the path to a manually exported Google Analytics custom report instead, e.g., `browserslist-ga --path my-manual-ga-export.csv`? Google Analytics allows exporting of custom reports, so I imagine this tool's documentation could specify the format of said custom report such that this tool could expect and work with a predictable format when the path is specified.

**Comment by galvarez421** [comment]
I went ahead and created https://github.com/galvarez421/browserslist-ga-export for this purpose, although I still think it could potentially be useful to roll this functionality into Browserslist-GA!

**Comment by dmfrancisco** [comment]
This looks very interesting, thanks for the suggestion 👍

**Comment by SalimBensiali** [comment]
Hi @dmfrancisco, any developments regarding this suggestion? Would you consider incorporating such functionality?

**Comment by dmfrancisco** [comment]
@SalimBensiali I'm not sure, @galvarez421's tool seems to work very well and maybe it makes sense to keep it as a separate project. @ai Maybe if everyone agrees it can be moved to the browserslist organization?

**Comment by ai** [comment]
@galvarez421 I gave you permission. Feel free to move the project to the `browserslist` org.

Ping me when you will move it. I will promote it in the docs and Twitter.

**Comment by SalimBensiali** [comment]
Thanks guys!

**Comment by galvarez421** [comment]
@ai Shall I transfer the repository to Browserslist organization? If so, I can do that tomorrow.

**Comment by ai** [comment]
Yeap, I have you membership in org if your accepted the invite on your email.

**Comment by galvarez421** [comment]
I have transferred the repository.

**Comment by ai** [comment]
Great. I added your tool to the “Tools” list and scheduled promotion tweet
