### ISSUE TITLE
Samsung Internet data missing from JSON output

### ISSUE THREAD

**Issue by Nooshu** [browserslist/browserslist-ga#8]
Hello,

I was looking into using this tool but the resulting `browserslist-stats.json` data is outputting 0 for all Samsung Internet (SI) versions:

```
"samsung": {
    "4": 0,
    "5": 0,
    "6.2": 0,
    "7.2": 0
  },
```

I'm using [this tool](https://github.com/galvarez421/browserslist-ga-export) to generate the JSON from a CSV rather than login directly. It pulls in the `caniuse-parser.js`. I can see the correct SI data in the CSV, just 0 in the output data. I believe this is because Samsung Internet isn't being parsed in [this file](https://github.com/browserslist/browserslist-ga/blob/master/src/caniuse-parser.js).

Thanks!

**Comment by albe** [comment]
Can confirm. We have around 5% Samsung Internet users and from that ~50% 7.2, but still the generated browserslist-stat from calling `npx browserslist-ga` shows:

```json
  "samsung": {
    "4": 0,
    "5": 0,
    "6.2": 0,
    "7.2": 0
  },
```

**Comment by jamespamplin** [comment]
Also having this issue. We've got 5% Samsung browser usage in the GA web interface.

**Comment by dmfrancisco** [comment]
Could you please try the following: If you import your Google Analytics data in [caniuse.com](https://caniuse.com/) (by clicking the cog icon and then "From Google Analytics: Import"), does Samsung appear in the "Browsers included" column? Thanks 👍

**Comment by jamespamplin** [comment]
@dmfrancisco interesting, on caniuse.com when I import, Samsung is in the **Browsers not included** column. Couldn't find the caniuse repo to raise/find the issue there.

![image](https://user-images.githubusercontent.com/2298529/51505114-99b07600-1ddc-11e9-9821-dcc5e2f5a66a.png)

**Comment by jamespamplin** [comment]
Thanks @dmfrancisco, raised the issue: Fyrd/caniuse#4742

**Comment by dmfrancisco** [comment]
@jamespamplin Thank you 👍Can you confirm that the issue was fixed on [caniuse.com](https://caniuse.com)? If it's working now, I'll implement the changes as soon as possible 🙂

**Comment by jamespamplin** [comment]
@dmfrancisco yep, all working now in caniuse.com - see Fyrd/caniuse#4742

**Comment by dmfrancisco** [comment]
Thanks for confirming 👍 I'll submit a PR this weekend with the changes

**Comment by rtymchyk** [comment]
@dmfrancisco @Nooshu is this fixed with that PR? I am still seeing all `0` for all Samsung Internet browsers, even though GA has a pretty high % on 8.2

**Comment by dmfrancisco** [comment]
@rtymchyk I think so but I don't have data to test. Could you confirm with the version on master (the NPM package hasn't been updated yet)?

**Comment by rtymchyk** [comment]
Oh oops, my bad, didn't realize it was not released yet. I will test and get back to you.

**Comment by rtymchyk** [comment]
<img width="262" alt="Screen Shot 2019-04-21 at 4 02 04 PM" src="https://user-images.githubusercontent.com/3498278/56474923-e0028900-644e-11e9-85ed-5ee1b721dc6a.png">

Looks good @dmfrancisco

**Comment by natewoodbridge** [comment]
This issue stills seems to be happening - I am getting zero results for Samsung, however in GA we have 5% for Samsung Internet 9.2. Using the `npx` command, so should be on the latest version.

![image](https://user-images.githubusercontent.com/123652/57694256-2c527a80-7643-11e9-9380-1519ff2e2dc9.png)

**Comment by dmfrancisco** [comment]
@natewoodbridge Are you using the NPM version? I haven't published the patch. Can you try it out with master? Sorry for the inconvenience.

**Comment by natewoodbridge** [comment]
Thank you @dmfrancisco. It's working when I use the `npx github:browserslist/browserslist-ga` command.

**Comment by rtymchyk** [comment]
Has this been released yet to NPM?

**Comment by davidstosik** [comment]
Doesn't seem so, I still get a straight `0`% for all Samsung browser versions whereas we have above 5% of users.

Using `npx github:browserslist/browserslist-ga` fixed it.
